# Site settings
title: Hauke Hillebrandt
description: Hauke Hillebrandt is a researcher and economist based in London, UK.
baseurl: "/portfolio"

# Build settings
markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
collections:
  pages:
    output: true
    permalink: /:name
  work:
    output: true
    permalink: /:name
